language: generic
sudo: false

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis

before_install:
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --skip --use
  - export EMACS=$(evm bin)
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask info
  - cask install
  - emacs --version
  - cask --version

matrix:
  fast_finish: true

script:
  - make deps test
